# Generated by Django 4.1.7 on 2023-02-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_profile_options_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Логін'),
        ),
    ]
